apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: nginx-server
      image: "davidetammaronutanix/nginx:2.0"
      ports:
          - containerPort: 80
